apiVersion: v1
kind: Service
metadata:
  name: qaserviceapi-service
spec:
  selector:
    app: qaserviceapi-pod
  ports:
  - port: 30023
    name: grpc
    nodePort: 30023
    targetPort: 30023
  - port: 30003
    name: http
    nodePort: 30003
    targetPort: 30003
  type: LoadBalancer